import Foundation

/// Real contact info, verified against the firm's own vCards
/// (`adlo-diy/sales-site/dist/assets/vcard/adlo-contact-*.vcf`, generated by
/// `tools/site-backup/build_sales_site.py`) and `adlo-case-estimator`'s
/// structured data — not placeholders.
enum FirmContact {
    static let firmName = "American Dream Law Office"
    /// The sales site's EN tracking number (`PHONE_I18N["en"]` in
    /// `build_sales_site.py`) — reused here rather than provisioning a
    /// separate number for the app, per that repo's existing per-channel
    /// tracking-number convention.
    static let phoneNumber = "+16562360205"
    static let phoneDisplay = "(656) 236-0205"
    static let whatsappNumber = "18889637326"
    /// No public email: the sales site has deliberately never displayed one
    /// (see the comment above `VCARD_TAGLINE_I18N` in `build_sales_site.py`)
    /// to avoid leaking the internal `intake@` notification address as if it
    /// were the firm's public one. Use `contactFormURL` instead.
    static let address = "10936 N 56th St, Suite 201, Temple Terrace, FL 33617"
    static let website = "https://americandreamlawoffice.com"
    static let contactFormURL = "https://www.americandreamlawoffice.com/contact/"
    static let consultationURL = "https://www.americandreamlawoffice.com/consultation/"
    /// EOIR has no public API — only this lookup website (A-Number, no login).
    /// The app links out to it directly rather than attempting to scrape it.
    static let eoirStatusURL = "https://acis.eoir.justice.gov/en/"
    /// Matches the `openingHours` in `adlo-case-estimator`'s LegalService
    /// structured data (`Mo-Fr 09:00-17:00`).
    static let officeHours = "Mon–Fri, 9:00 AM – 5:00 PM ET"
}
