import Foundation

/// Real contact info, verified against the firm's own vCards
/// (`adlo-diy/sales-site/dist/assets/vcard/adlo-contact-*.vcf`, generated by
/// `tools/site-backup/build_sales_site.py`) and `adlo-case-estimator`'s
/// structured data — not placeholders.
enum FirmContact {
    static let firmName = "American Dream Law Office"
    /// The sales site's EN tracking number (`PHONE_I18N["en"]` in
    /// `build_sales_site.py`) — reused here rather than provisioning a
    /// separate number for the app, per that repo's existing per-channel
    /// tracking-number convention.
    static let phoneNumber = "+16562360205"
    static let phoneDisplay = "(656) 236-0205"
    static let whatsappNumber = "18889637326"
    /// Track-specific inbox — new/potential clients (`AccountType.prospect`)
    /// go to intake, existing clients (`AccountType.client`) go straight to
    /// the clients inbox. The sales site itself never publicly displays an
    /// email (see `VCARD_TAGLINE_I18N` in `build_sales_site.py`) — this is
    /// specific to the app's own two tracks, provided directly rather than
    /// inferred from that policy.
    static func contactEmail(for accountType: AccountType) -> String {
        switch accountType {
        case .client: return "clients@americandreamlawoffice.com"
        case .prospect: return "intake@americandreamlawoffice.com"
        }
    }
    static let address = "10936 N 56th St, Suite 201, Temple Terrace, FL 33617"
    static let website = "https://americandreamlawoffice.com"
    static let consultationURL = "https://www.americandreamlawoffice.com/consultation/"
    /// One combined team page for the whole firm — attorneys, paralegals,
    /// legal assistants, and office staff all appear together
    /// (`/our-firm/{slug}/` per person in `build_sales_site.py`). There's no
    /// separate "legal staff" vs. "intake staff" page on the real site, so
    /// both tracks point here rather than to an invented split.
    static let teamURL = "https://americandreamlawoffice.com/our-firm/"
    /// EOIR has no public API — only this lookup website (A-Number, no login).
    /// The app links out to it directly rather than attempting to scrape it.
    static let eoirStatusURL = "https://acis.eoir.justice.gov/en/"
    /// Matches the `openingHours` in `adlo-case-estimator`'s LegalService
    /// structured data (`Mo-Fr 09:00-17:00`).
    static let officeHours = "Mon–Fri, 9:00 AM – 5:00 PM ET"

    struct SocialLink: Identifiable {
        let name: String
        let url: String
        /// No official SF Symbol exists for any of these brands' logos —
        /// this is a generic external-link glyph, not a stand-in for the
        /// real brand mark.
        let systemImage = "arrow.up.forward.app"
        var id: String { name }
    }

    /// Matches `SOCIAL_LINKS` in `adlo-diy/tools/site-backup/build_sales_site.py`
    /// (the sales site's own "Follow Us" footer) — same accounts, same order.
    static let socialLinks: [SocialLink] = [
        SocialLink(name: "YouTube", url: "https://www.youtube.com/channel/UCSe2eLA-Bgf50upNxthD2fg"),
        SocialLink(name: "Instagram", url: "https://www.instagram.com/americandreamlawoffice/"),
        SocialLink(name: "Facebook", url: "https://www.facebook.com/1413258232335199"),
        SocialLink(name: "TikTok", url: "https://www.tiktok.com/@adloimmigration"),
        SocialLink(name: "Threads", url: "https://www.threads.net/@americandreamlawoffice"),
        SocialLink(name: "LinkedIn", url: "https://www.linkedin.com/company/10245091/"),
    ]
}
